name: Triggering another  Workflow 

on:
  workflow_run:
    workflows: ["My workflow"]
    types:
      - completed

jobs:
  trigger-another-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      #- name: Invoke workflow without inputs. Wait for result
       # uses: aurelien-baudet/workflow-dispatch@v2
        #with:
         # workflow: My workflows
          #token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Invoke workflow without inputs. Don't wait for result
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: KenyaEMR CI
          repo: palladiumkenya/esm-stock-management
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: false
