name: Trigger Workflow 1

on:
  workflow_run:
    workflows: ["My workflow"]
    types:
      - completed

jobs:
  trigger-another-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Invoke workflow without inputs. Wait for result
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: My Workflow
          token: ${{ secrets.PERSONAL_TOKEN }}
