name: My workflow
on: [push]
# grouping jobs
jobs:
# job to run cypress
 cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node:version: '14'
      - name: Install dependencies
        run: npm install  --force or --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
            install: false
            start: npm start
            wait-on: "http://localhost:3000"

 deploy-to-server:
    runs-on: ubuntu-latest
    needs:  cypress-run
    steps:
    - name: Prepare Directory
      shell: bash
      run: |
        sudo mkdir testing
        
    - name: deploy-to-server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: '-p ${{secrets.PORT}}'
        src: '~/testing'
        dest: '${{secrets.USER}}@${{secrets.HOST}}:/home/${{secrets.USER}}/testing'
